# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import serial,configparser
from PyQt5.QtWidgets import QApplication, QMainWindow

import res_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(320, 460))
        Form.setMaximumSize(QtCore.QSize(320, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/q/q/hj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/q/q/t.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_9.setStatusTip("")
        self.pushButton_9.setWhatsThis("")
        self.pushButton_9.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/q/q/U.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_11.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_11.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/q/q/L.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_7.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/q/q/R.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 50))
        self.pushButton_10.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/q/q/D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:1px groove gray;border-radius:10px;padding:1px 4px;border-style: outset;}\n"
"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\n"
"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.pushButton_9.pressed.connect(self.uup)
        self.pushButton_7.pressed.connect(self.rri)
        self.pushButton_11.pressed.connect(self.lle)
        self.pushButton_10.pressed.connect(self.ddo)
        self.pushButton_6.pressed.connect(self.ffa)
        self.pushButton_2.pressed.connect(self.ffb)
        self.pushButton_3.pressed.connect(self.iia)
        self.pushButton_4.pressed.connect(self.iib)
        self.pushButton_9.released.connect(self.st)
        self.pushButton_11.released.connect(self.st)
        self.pushButton_7.released.connect(self.st)
        self.pushButton_10.released.connect(self.st)
        self.pushButton_6.released.connect(self.st)
        self.pushButton_2.released.connect(self.st)
        self.pushButton_3.released.connect(self.st)
        self.pushButton_4.released.connect(self.st)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ElectricVideoAdapter"))
        self.pushButton_9.setToolTip(_translate("Form", "Up"))
        self.pushButton_9.setShortcut(_translate("Form", "Up"))
        self.pushButton_11.setToolTip(_translate("Form", "Left"))
        self.pushButton_11.setShortcut(_translate("Form", "Left"))
        self.pushButton_7.setToolTip(_translate("Form", "Right"))
        self.pushButton_7.setShortcut(_translate("Form", "Right"))
        self.pushButton_10.setToolTip(_translate("Form", "Down"))
        self.pushButton_10.setShortcut(_translate("Form", "Down"))
        self.pushButton_6.setToolTip(_translate("Form", "Focus-"))
        self.pushButton_6.setText(_translate("Form", "F-"))
        self.pushButton_6.setShortcut(_translate("Form", "F"))
        self.pushButton_2.setToolTip(_translate("Form", "Focus+"))
        self.pushButton_2.setText(_translate("Form", "F+"))
        self.pushButton_2.setShortcut(_translate("Form", "G"))
        self.pushButton_3.setToolTip(_translate("Form", "Iris-"))
        self.pushButton_3.setText(_translate("Form", "I-"))
        self.pushButton_3.setShortcut(_translate("Form", "I"))
        self.pushButton_4.setToolTip(_translate("Form", "Iris+"))
        self.pushButton_4.setText(_translate("Form", "I+"))
        self.pushButton_4.setShortcut(_translate("Form", "O"))

    def wt(self,n):
        try:
            s.write(n)
        except Exception as e:
            print("could not open serial port",e)

    def st(self):
        d = bytes.fromhex('00')
        self.wt(d)

    def ffa(self):
        d = bytes.fromhex('56')
        self.wt(d)

    def ffb(self):
        d = bytes.fromhex('65')
        self.wt(d)

    def iia(self):
        d = bytes.fromhex('34')
        self.wt(d)

    def iib(self):
        d = bytes.fromhex('43')
        self.wt(d)

    def uup(self):
        d = bytes.fromhex('12')
        self.wt(d)

    def ddo(self):
        d = bytes.fromhex('21')
        self.wt(d)

    def lle(self):
       d = bytes.fromhex('78')
       self.wt(d)

    def rri(self):
        d = bytes.fromhex('87')
        self.wt(d)

if __name__ == "__main__":
    import sys
    cp = configparser.ConfigParser()
    cp.read('sp.ini')
    conn=cp.get('com', 'serialPort')

    try:
        s = serial.Serial(conn, 9600, timeout=0.5)
        # s = serial.Serial("/dev/tty.usbserial-1710", 9600, timeout=0.5)
    except Exception as e:
        print(e)

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
